// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: automation_logs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const clearAllAutomationLogs = `-- name: ClearAllAutomationLogs :exec
DELETE FROM automation_logs
`

func (q *Queries) ClearAllAutomationLogs(ctx context.Context) error {
	_, err := q.exec(ctx, q.clearAllAutomationLogsStmt, clearAllAutomationLogs)
	return err
}

const countAutomationLogs = `-- name: CountAutomationLogs :one

SELECT COUNT(*) FROM automation_logs
`

// ==========================================
// COUNT OPERATIONS
// ==========================================
func (q *Queries) CountAutomationLogs(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countAutomationLogsStmt, countAutomationLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAutomationLogsByAction = `-- name: CountAutomationLogsByAction :one
SELECT COUNT(*) FROM automation_logs
WHERE action_type = ?
`

func (q *Queries) CountAutomationLogsByAction(ctx context.Context, actionType string) (int64, error) {
	row := q.queryRow(ctx, q.countAutomationLogsByActionStmt, countAutomationLogsByAction, actionType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAutomationLogsByName = `-- name: CountAutomationLogsByName :one
SELECT COUNT(*) FROM automation_logs
WHERE name = ?
`

func (q *Queries) CountAutomationLogsByName(ctx context.Context, name string) (int64, error) {
	row := q.queryRow(ctx, q.countAutomationLogsByNameStmt, countAutomationLogsByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFailedLogs = `-- name: CountFailedLogs :one
SELECT COUNT(*) FROM automation_logs
WHERE success = FALSE
`

func (q *Queries) CountFailedLogs(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countFailedLogsStmt, countFailedLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLogsByDateRange = `-- name: CountLogsByDateRange :one
SELECT COUNT(*) FROM automation_logs
WHERE create_at BETWEEN ? AND ?
`

type CountLogsByDateRangeParams struct {
	FromCreateAt sql.NullTime `json:"from_create_at"`
	ToCreateAt   sql.NullTime `json:"to_create_at"`
}

func (q *Queries) CountLogsByDateRange(ctx context.Context, arg CountLogsByDateRangeParams) (int64, error) {
	row := q.queryRow(ctx, q.countLogsByDateRangeStmt, countLogsByDateRange, arg.FromCreateAt, arg.ToCreateAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentLogs = `-- name: CountRecentLogs :one
SELECT COUNT(*) FROM automation_logs
WHERE create_at >= datetime('now', '-1 hour')
`

func (q *Queries) CountRecentLogs(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countRecentLogsStmt, countRecentLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuccessfulLogs = `-- name: CountSuccessfulLogs :one
SELECT COUNT(*) FROM automation_logs
WHERE success = TRUE
`

func (q *Queries) CountSuccessfulLogs(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countSuccessfulLogsStmt, countSuccessfulLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodaysLogs = `-- name: CountTodaysLogs :one
SELECT COUNT(*) FROM automation_logs
WHERE date(create_at) = date('now')
`

func (q *Queries) CountTodaysLogs(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countTodaysLogsStmt, countTodaysLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAutomationLog = `-- name: CreateAutomationLog :one


INSERT INTO automation_logs (
    name, title, action_type, x_position, y_position, pixel_color, success, error_message
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message
`

type CreateAutomationLogParams struct {
	Name         string          `json:"name"`
	Title        string          `json:"title"`
	ActionType   string          `json:"action_type"`
	XPosition    sql.NullFloat64 `json:"x_position"`
	YPosition    sql.NullFloat64 `json:"y_position"`
	PixelColor   sql.NullString  `json:"pixel_color"`
	Success      sql.NullBool    `json:"success"`
	ErrorMessage sql.NullString  `json:"error_message"`
}

// ==========================================
// CREATE OPERATIONS
// ==========================================
func (q *Queries) CreateAutomationLog(ctx context.Context, arg CreateAutomationLogParams) (AutomationLog, error) {
	row := q.queryRow(ctx, q.createAutomationLogStmt, createAutomationLog,
		arg.Name,
		arg.Title,
		arg.ActionType,
		arg.XPosition,
		arg.YPosition,
		arg.PixelColor,
		arg.Success,
		arg.ErrorMessage,
	)
	var i AutomationLog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.ActionType,
		&i.XPosition,
		&i.YPosition,
		&i.PixelColor,
		&i.CreateAt,
		&i.Success,
		&i.ErrorMessage,
	)
	return i, err
}

const createAutomationLogWithTimestamp = `-- name: CreateAutomationLogWithTimestamp :one
INSERT INTO automation_logs (
    name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message
`

type CreateAutomationLogWithTimestampParams struct {
	Name         string          `json:"name"`
	Title        string          `json:"title"`
	ActionType   string          `json:"action_type"`
	XPosition    sql.NullFloat64 `json:"x_position"`
	YPosition    sql.NullFloat64 `json:"y_position"`
	PixelColor   sql.NullString  `json:"pixel_color"`
	CreateAt     sql.NullTime    `json:"create_at"`
	Success      sql.NullBool    `json:"success"`
	ErrorMessage sql.NullString  `json:"error_message"`
}

func (q *Queries) CreateAutomationLogWithTimestamp(ctx context.Context, arg CreateAutomationLogWithTimestampParams) (AutomationLog, error) {
	row := q.queryRow(ctx, q.createAutomationLogWithTimestampStmt, createAutomationLogWithTimestamp,
		arg.Name,
		arg.Title,
		arg.ActionType,
		arg.XPosition,
		arg.YPosition,
		arg.PixelColor,
		arg.CreateAt,
		arg.Success,
		arg.ErrorMessage,
	)
	var i AutomationLog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.ActionType,
		&i.XPosition,
		&i.YPosition,
		&i.PixelColor,
		&i.CreateAt,
		&i.Success,
		&i.ErrorMessage,
	)
	return i, err
}

const deleteAutomationLog = `-- name: DeleteAutomationLog :exec

DELETE FROM automation_logs
WHERE id = ?
`

// ==========================================
// DELETE OPERATIONS
// ==========================================
func (q *Queries) DeleteAutomationLog(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteAutomationLogStmt, deleteAutomationLog, id)
	return err
}

const deleteAutomationLogsByAction = `-- name: DeleteAutomationLogsByAction :exec
DELETE FROM automation_logs
WHERE action_type = ?
`

func (q *Queries) DeleteAutomationLogsByAction(ctx context.Context, actionType string) error {
	_, err := q.exec(ctx, q.deleteAutomationLogsByActionStmt, deleteAutomationLogsByAction, actionType)
	return err
}

const deleteAutomationLogsByName = `-- name: DeleteAutomationLogsByName :exec
DELETE FROM automation_logs
WHERE name = ?
`

func (q *Queries) DeleteAutomationLogsByName(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.deleteAutomationLogsByNameStmt, deleteAutomationLogsByName, name)
	return err
}

const deleteFailedLogs = `-- name: DeleteFailedLogs :exec
DELETE FROM automation_logs
WHERE success = FALSE
`

func (q *Queries) DeleteFailedLogs(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteFailedLogsStmt, deleteFailedLogs)
	return err
}

const deleteLogsByDateRange = `-- name: DeleteLogsByDateRange :exec
DELETE FROM automation_logs
WHERE create_at BETWEEN ? AND ?
`

type DeleteLogsByDateRangeParams struct {
	FromCreateAt sql.NullTime `json:"from_create_at"`
	ToCreateAt   sql.NullTime `json:"to_create_at"`
}

func (q *Queries) DeleteLogsByDateRange(ctx context.Context, arg DeleteLogsByDateRangeParams) error {
	_, err := q.exec(ctx, q.deleteLogsByDateRangeStmt, deleteLogsByDateRange, arg.FromCreateAt, arg.ToCreateAt)
	return err
}

const deleteOldAutomationLogs = `-- name: DeleteOldAutomationLogs :exec
DELETE FROM automation_logs
WHERE create_at < datetime('now', '-7 days')
`

func (q *Queries) DeleteOldAutomationLogs(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteOldAutomationLogsStmt, deleteOldAutomationLogs)
	return err
}

const deleteOldAutomationLogsByDays = `-- name: DeleteOldAutomationLogsByDays :exec
DELETE FROM automation_logs
WHERE create_at < datetime('now', '-' || ? || ' days')
`

func (q *Queries) DeleteOldAutomationLogsByDays(ctx context.Context, dollar_1 sql.NullString) error {
	_, err := q.exec(ctx, q.deleteOldAutomationLogsByDaysStmt, deleteOldAutomationLogsByDays, dollar_1)
	return err
}

const getActionTypeSummary = `-- name: GetActionTypeSummary :many

SELECT 
    action_type,
    COUNT(*) as total_count,
    SUM(CASE WHEN success = TRUE THEN 1 ELSE 0 END) as success_count,
    SUM(CASE WHEN success = FALSE THEN 1 ELSE 0 END) as failed_count,
    MIN(create_at) as first_occurrence,
    MAX(create_at) as last_occurrence
FROM automation_logs
GROUP BY action_type
ORDER BY total_count DESC
`

type GetActionTypeSummaryRow struct {
	ActionType      string          `json:"action_type"`
	TotalCount      int64           `json:"total_count"`
	SuccessCount    sql.NullFloat64 `json:"success_count"`
	FailedCount     sql.NullFloat64 `json:"failed_count"`
	FirstOccurrence interface{}     `json:"first_occurrence"`
	LastOccurrence  interface{}     `json:"last_occurrence"`
}

// ==========================================
// AGGREGATE OPERATIONS
// ==========================================
func (q *Queries) GetActionTypeSummary(ctx context.Context) ([]GetActionTypeSummaryRow, error) {
	rows, err := q.query(ctx, q.getActionTypeSummaryStmt, getActionTypeSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActionTypeSummaryRow{}
	for rows.Next() {
		var i GetActionTypeSummaryRow
		if err := rows.Scan(
			&i.ActionType,
			&i.TotalCount,
			&i.SuccessCount,
			&i.FailedCount,
			&i.FirstOccurrence,
			&i.LastOccurrence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAutomationLog = `-- name: GetAutomationLog :one

SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE id = ? LIMIT 1
`

// ==========================================
// READ OPERATIONS - Single Record
// ==========================================
func (q *Queries) GetAutomationLog(ctx context.Context, id int64) (AutomationLog, error) {
	row := q.queryRow(ctx, q.getAutomationLogStmt, getAutomationLog, id)
	var i AutomationLog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.ActionType,
		&i.XPosition,
		&i.YPosition,
		&i.PixelColor,
		&i.CreateAt,
		&i.Success,
		&i.ErrorMessage,
	)
	return i, err
}

const getAutomationLogByName = `-- name: GetAutomationLogByName :one
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE name = ? 
ORDER BY create_at DESC 
LIMIT 1
`

func (q *Queries) GetAutomationLogByName(ctx context.Context, name string) (AutomationLog, error) {
	row := q.queryRow(ctx, q.getAutomationLogByNameStmt, getAutomationLogByName, name)
	var i AutomationLog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.ActionType,
		&i.XPosition,
		&i.YPosition,
		&i.PixelColor,
		&i.CreateAt,
		&i.Success,
		&i.ErrorMessage,
	)
	return i, err
}

const getDailySummary = `-- name: GetDailySummary :many
SELECT 
    date(create_at) as log_date,
    COUNT(*) as total_logs,
    SUM(CASE WHEN success = TRUE THEN 1 ELSE 0 END) as successful_logs,
    SUM(CASE WHEN success = FALSE THEN 1 ELSE 0 END) as failed_logs
FROM automation_logs
WHERE create_at >= date('now', '-30 days')
GROUP BY date(create_at)
ORDER BY log_date DESC
`

type GetDailySummaryRow struct {
	LogDate        interface{}     `json:"log_date"`
	TotalLogs      int64           `json:"total_logs"`
	SuccessfulLogs sql.NullFloat64 `json:"successful_logs"`
	FailedLogs     sql.NullFloat64 `json:"failed_logs"`
}

func (q *Queries) GetDailySummary(ctx context.Context) ([]GetDailySummaryRow, error) {
	rows, err := q.query(ctx, q.getDailySummaryStmt, getDailySummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailySummaryRow{}
	for rows.Next() {
		var i GetDailySummaryRow
		if err := rows.Scan(
			&i.LogDate,
			&i.TotalLogs,
			&i.SuccessfulLogs,
			&i.FailedLogs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDatabaseStats = `-- name: GetDatabaseStats :one

SELECT 
    COUNT(*) as total_logs,
    COUNT(DISTINCT action_type) as unique_actions,
    COUNT(DISTINCT name) as unique_names,
    MIN(create_at) as oldest_log,
    MAX(create_at) as newest_log,
    SUM(CASE WHEN success = TRUE THEN 1 ELSE 0 END) as total_successful,
    SUM(CASE WHEN success = FALSE THEN 1 ELSE 0 END) as total_failed
FROM automation_logs
`

type GetDatabaseStatsRow struct {
	TotalLogs       int64           `json:"total_logs"`
	UniqueActions   int64           `json:"unique_actions"`
	UniqueNames     int64           `json:"unique_names"`
	OldestLog       interface{}     `json:"oldest_log"`
	NewestLog       interface{}     `json:"newest_log"`
	TotalSuccessful sql.NullFloat64 `json:"total_successful"`
	TotalFailed     sql.NullFloat64 `json:"total_failed"`
}

// ==========================================
// UTILITY OPERATIONS
// ==========================================
func (q *Queries) GetDatabaseStats(ctx context.Context) (GetDatabaseStatsRow, error) {
	row := q.queryRow(ctx, q.getDatabaseStatsStmt, getDatabaseStats)
	var i GetDatabaseStatsRow
	err := row.Scan(
		&i.TotalLogs,
		&i.UniqueActions,
		&i.UniqueNames,
		&i.OldestLog,
		&i.NewestLog,
		&i.TotalSuccessful,
		&i.TotalFailed,
	)
	return i, err
}

const getHourlySummary = `-- name: GetHourlySummary :many
SELECT 
    strftime('%Y-%m-%d %H:00:00', create_at) as hour_slot,
    COUNT(*) as total_logs,
    SUM(CASE WHEN success = TRUE THEN 1 ELSE 0 END) as successful_logs,
    SUM(CASE WHEN success = FALSE THEN 1 ELSE 0 END) as failed_logs
FROM automation_logs
WHERE create_at >= datetime('now', '-24 hours')
GROUP BY strftime('%Y-%m-%d %H', create_at)
ORDER BY hour_slot DESC
`

type GetHourlySummaryRow struct {
	HourSlot       interface{}     `json:"hour_slot"`
	TotalLogs      int64           `json:"total_logs"`
	SuccessfulLogs sql.NullFloat64 `json:"successful_logs"`
	FailedLogs     sql.NullFloat64 `json:"failed_logs"`
}

func (q *Queries) GetHourlySummary(ctx context.Context) ([]GetHourlySummaryRow, error) {
	rows, err := q.query(ctx, q.getHourlySummaryStmt, getHourlySummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHourlySummaryRow{}
	for rows.Next() {
		var i GetHourlySummaryRow
		if err := rows.Scan(
			&i.HourSlot,
			&i.TotalLogs,
			&i.SuccessfulLogs,
			&i.FailedLogs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestAutomationLog = `-- name: GetLatestAutomationLog :one
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
ORDER BY create_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAutomationLog(ctx context.Context) (AutomationLog, error) {
	row := q.queryRow(ctx, q.getLatestAutomationLogStmt, getLatestAutomationLog)
	var i AutomationLog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.ActionType,
		&i.XPosition,
		&i.YPosition,
		&i.PixelColor,
		&i.CreateAt,
		&i.Success,
		&i.ErrorMessage,
	)
	return i, err
}

const getLatestFailedLog = `-- name: GetLatestFailedLog :one
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE success = FALSE
ORDER BY create_at DESC
LIMIT 1
`

func (q *Queries) GetLatestFailedLog(ctx context.Context) (AutomationLog, error) {
	row := q.queryRow(ctx, q.getLatestFailedLogStmt, getLatestFailedLog)
	var i AutomationLog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.ActionType,
		&i.XPosition,
		&i.YPosition,
		&i.PixelColor,
		&i.CreateAt,
		&i.Success,
		&i.ErrorMessage,
	)
	return i, err
}

const getLatestSuccessfulLog = `-- name: GetLatestSuccessfulLog :one
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE success = TRUE
ORDER BY create_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSuccessfulLog(ctx context.Context) (AutomationLog, error) {
	row := q.queryRow(ctx, q.getLatestSuccessfulLogStmt, getLatestSuccessfulLog)
	var i AutomationLog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.ActionType,
		&i.XPosition,
		&i.YPosition,
		&i.PixelColor,
		&i.CreateAt,
		&i.Success,
		&i.ErrorMessage,
	)
	return i, err
}

const getLogSizeByAction = `-- name: GetLogSizeByAction :many
SELECT 
    action_type,
    COUNT(*) as log_count,
    ROUND(AVG(LENGTH(COALESCE(error_message, ''))), 2) as avg_error_msg_length
FROM automation_logs
GROUP BY action_type
ORDER BY log_count DESC
`

type GetLogSizeByActionRow struct {
	ActionType        string  `json:"action_type"`
	LogCount          int64   `json:"log_count"`
	AvgErrorMsgLength float64 `json:"avg_error_msg_length"`
}

func (q *Queries) GetLogSizeByAction(ctx context.Context) ([]GetLogSizeByActionRow, error) {
	rows, err := q.query(ctx, q.getLogSizeByActionStmt, getLogSizeByAction)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLogSizeByActionRow{}
	for rows.Next() {
		var i GetLogSizeByActionRow
		if err := rows.Scan(&i.ActionType, &i.LogCount, &i.AvgErrorMsgLength); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogsFromLastDays = `-- name: GetLogsFromLastDays :many
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE create_at >= datetime('now', '-' || ? || ' days')
ORDER BY create_at DESC
`

func (q *Queries) GetLogsFromLastDays(ctx context.Context, dollar_1 sql.NullString) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.getLogsFromLastDaysStmt, getLogsFromLastDays, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogsFromLastHours = `-- name: GetLogsFromLastHours :many
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE create_at >= datetime('now', '-' || ? || ' hours')
ORDER BY create_at DESC
`

func (q *Queries) GetLogsFromLastHours(ctx context.Context, dollar_1 sql.NullString) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.getLogsFromLastHoursStmt, getLogsFromLastHours, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogsFromLastMinutes = `-- name: GetLogsFromLastMinutes :many
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE create_at >= datetime('now', '-' || ? || ' minutes')
ORDER BY create_at DESC
`

func (q *Queries) GetLogsFromLastMinutes(ctx context.Context, dollar_1 sql.NullString) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.getLogsFromLastMinutesStmt, getLogsFromLastMinutes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMostCommonPixelColors = `-- name: GetMostCommonPixelColors :many
SELECT 
    pixel_color,
    COUNT(*) as occurrence_count,
    MAX(create_at) as last_seen
FROM automation_logs
WHERE pixel_color IS NOT NULL
GROUP BY pixel_color
ORDER BY occurrence_count DESC
LIMIT ?
`

type GetMostCommonPixelColorsRow struct {
	PixelColor      sql.NullString `json:"pixel_color"`
	OccurrenceCount int64          `json:"occurrence_count"`
	LastSeen        interface{}    `json:"last_seen"`
}

func (q *Queries) GetMostCommonPixelColors(ctx context.Context, limit int64) ([]GetMostCommonPixelColorsRow, error) {
	rows, err := q.query(ctx, q.getMostCommonPixelColorsStmt, getMostCommonPixelColors, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMostCommonPixelColorsRow{}
	for rows.Next() {
		var i GetMostCommonPixelColorsRow
		if err := rows.Scan(&i.PixelColor, &i.OccurrenceCount, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMostUsedPositions = `-- name: GetMostUsedPositions :many
SELECT 
    x_position,
    y_position,
    COUNT(*) as usage_count,
    MAX(create_at) as last_used
FROM automation_logs
WHERE x_position IS NOT NULL AND y_position IS NOT NULL
GROUP BY x_position, y_position
ORDER BY usage_count DESC
LIMIT ?
`

type GetMostUsedPositionsRow struct {
	XPosition  sql.NullFloat64 `json:"x_position"`
	YPosition  sql.NullFloat64 `json:"y_position"`
	UsageCount int64           `json:"usage_count"`
	LastUsed   interface{}     `json:"last_used"`
}

func (q *Queries) GetMostUsedPositions(ctx context.Context, limit int64) ([]GetMostUsedPositionsRow, error) {
	rows, err := q.query(ctx, q.getMostUsedPositionsStmt, getMostUsedPositions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMostUsedPositionsRow{}
	for rows.Next() {
		var i GetMostUsedPositionsRow
		if err := rows.Scan(
			&i.XPosition,
			&i.YPosition,
			&i.UsageCount,
			&i.LastUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentAutomationLogs = `-- name: GetRecentAutomationLogs :many

SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE create_at >= datetime('now', '-1 hour')
ORDER BY create_at DESC
`

// ==========================================
// READ OPERATIONS - Time-based Queries
// ==========================================
func (q *Queries) GetRecentAutomationLogs(ctx context.Context) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.getRecentAutomationLogsStmt, getRecentAutomationLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodaysLogs = `-- name: GetTodaysLogs :many
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE date(create_at) = date('now')
ORDER BY create_at DESC
`

func (q *Queries) GetTodaysLogs(ctx context.Context) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.getTodaysLogsStmt, getTodaysLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYesterdaysLogs = `-- name: GetYesterdaysLogs :many
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE date(create_at) = date('now', '-1 day')
ORDER BY create_at DESC
`

func (q *Queries) GetYesterdaysLogs(ctx context.Context) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.getYesterdaysLogsStmt, getYesterdaysLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationLogs = `-- name: ListAutomationLogs :many

SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
ORDER BY create_at DESC
LIMIT ?
`

// ==========================================
// READ OPERATIONS - Multiple Records
// ==========================================
func (q *Queries) ListAutomationLogs(ctx context.Context, limit int64) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.listAutomationLogsStmt, listAutomationLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationLogsByAction = `-- name: ListAutomationLogsByAction :many
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE action_type = ?
ORDER BY create_at DESC
LIMIT ?
`

type ListAutomationLogsByActionParams struct {
	ActionType string `json:"action_type"`
	Limit      int64  `json:"limit"`
}

func (q *Queries) ListAutomationLogsByAction(ctx context.Context, arg ListAutomationLogsByActionParams) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.listAutomationLogsByActionStmt, listAutomationLogsByAction, arg.ActionType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationLogsByName = `-- name: ListAutomationLogsByName :many
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE name = ?
ORDER BY create_at DESC
LIMIT ?
`

type ListAutomationLogsByNameParams struct {
	Name  string `json:"name"`
	Limit int64  `json:"limit"`
}

func (q *Queries) ListAutomationLogsByName(ctx context.Context, arg ListAutomationLogsByNameParams) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.listAutomationLogsByNameStmt, listAutomationLogsByName, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationLogsByTitle = `-- name: ListAutomationLogsByTitle :many
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE title LIKE '%' || ? || '%'
ORDER BY create_at DESC
LIMIT ?
`

type ListAutomationLogsByTitleParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int64          `json:"limit"`
}

func (q *Queries) ListAutomationLogsByTitle(ctx context.Context, arg ListAutomationLogsByTitleParams) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.listAutomationLogsByTitleStmt, listAutomationLogsByTitle, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedLogs = `-- name: ListFailedLogs :many
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE success = FALSE
ORDER BY create_at DESC
LIMIT ?
`

func (q *Queries) ListFailedLogs(ctx context.Context, limit int64) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.listFailedLogsStmt, listFailedLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsByDateRange = `-- name: ListLogsByDateRange :many
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE create_at BETWEEN ? AND ?
ORDER BY create_at DESC
`

type ListLogsByDateRangeParams struct {
	FromCreateAt sql.NullTime `json:"from_create_at"`
	ToCreateAt   sql.NullTime `json:"to_create_at"`
}

func (q *Queries) ListLogsByDateRange(ctx context.Context, arg ListLogsByDateRangeParams) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.listLogsByDateRangeStmt, listLogsByDateRange, arg.FromCreateAt, arg.ToCreateAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsByPixelColor = `-- name: ListLogsByPixelColor :many
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE pixel_color = ?
ORDER BY create_at DESC
LIMIT ?
`

type ListLogsByPixelColorParams struct {
	PixelColor sql.NullString `json:"pixel_color"`
	Limit      int64          `json:"limit"`
}

func (q *Queries) ListLogsByPixelColor(ctx context.Context, arg ListLogsByPixelColorParams) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.listLogsByPixelColorStmt, listLogsByPixelColor, arg.PixelColor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsByPosition = `-- name: ListLogsByPosition :many
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE x_position = ? AND y_position = ?
ORDER BY create_at DESC
LIMIT ?
`

type ListLogsByPositionParams struct {
	XPosition sql.NullFloat64 `json:"x_position"`
	YPosition sql.NullFloat64 `json:"y_position"`
	Limit     int64           `json:"limit"`
}

func (q *Queries) ListLogsByPosition(ctx context.Context, arg ListLogsByPositionParams) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.listLogsByPositionStmt, listLogsByPosition, arg.XPosition, arg.YPosition, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuccessfulLogs = `-- name: ListSuccessfulLogs :many
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE success = TRUE
ORDER BY create_at DESC
LIMIT ?
`

func (q *Queries) ListSuccessfulLogs(ctx context.Context, limit int64) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.listSuccessfulLogsStmt, listSuccessfulLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLogsByErrorMessage = `-- name: SearchLogsByErrorMessage :many

SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE error_message LIKE '%' || ? || '%'
ORDER BY create_at DESC
LIMIT ?
`

type SearchLogsByErrorMessageParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int64          `json:"limit"`
}

// ==========================================
// SEARCH OPERATIONS
// ==========================================
func (q *Queries) SearchLogsByErrorMessage(ctx context.Context, arg SearchLogsByErrorMessageParams) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.searchLogsByErrorMessageStmt, searchLogsByErrorMessage, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLogsByNameOrTitle = `-- name: SearchLogsByNameOrTitle :many
SELECT id, name, title, action_type, x_position, y_position, pixel_color, create_at, success, error_message FROM automation_logs
WHERE name LIKE '%' || ? || '%' OR title LIKE '%' || ? || '%'
ORDER BY create_at DESC
LIMIT ?
`

type SearchLogsByNameOrTitleParams struct {
	Column1 sql.NullString `json:"column_1"`
	Column2 sql.NullString `json:"column_2"`
	Limit   int64          `json:"limit"`
}

func (q *Queries) SearchLogsByNameOrTitle(ctx context.Context, arg SearchLogsByNameOrTitleParams) ([]AutomationLog, error) {
	rows, err := q.query(ctx, q.searchLogsByNameOrTitleStmt, searchLogsByNameOrTitle, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationLog{}
	for rows.Next() {
		var i AutomationLog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.ActionType,
			&i.XPosition,
			&i.YPosition,
			&i.PixelColor,
			&i.CreateAt,
			&i.Success,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAutomationLogName = `-- name: UpdateAutomationLogName :exec
UPDATE automation_logs
SET name = ?
WHERE id = ?
`

type UpdateAutomationLogNameParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateAutomationLogName(ctx context.Context, arg UpdateAutomationLogNameParams) error {
	_, err := q.exec(ctx, q.updateAutomationLogNameStmt, updateAutomationLogName, arg.Name, arg.ID)
	return err
}

const updateAutomationLogPixelColor = `-- name: UpdateAutomationLogPixelColor :exec
UPDATE automation_logs
SET pixel_color = ?
WHERE id = ?
`

type UpdateAutomationLogPixelColorParams struct {
	PixelColor sql.NullString `json:"pixel_color"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateAutomationLogPixelColor(ctx context.Context, arg UpdateAutomationLogPixelColorParams) error {
	_, err := q.exec(ctx, q.updateAutomationLogPixelColorStmt, updateAutomationLogPixelColor, arg.PixelColor, arg.ID)
	return err
}

const updateAutomationLogPosition = `-- name: UpdateAutomationLogPosition :exec
UPDATE automation_logs
SET x_position = ?, y_position = ?
WHERE id = ?
`

type UpdateAutomationLogPositionParams struct {
	XPosition sql.NullFloat64 `json:"x_position"`
	YPosition sql.NullFloat64 `json:"y_position"`
	ID        int64           `json:"id"`
}

func (q *Queries) UpdateAutomationLogPosition(ctx context.Context, arg UpdateAutomationLogPositionParams) error {
	_, err := q.exec(ctx, q.updateAutomationLogPositionStmt, updateAutomationLogPosition, arg.XPosition, arg.YPosition, arg.ID)
	return err
}

const updateAutomationLogSuccess = `-- name: UpdateAutomationLogSuccess :exec

UPDATE automation_logs
SET success = ?, error_message = ?
WHERE id = ?
`

type UpdateAutomationLogSuccessParams struct {
	Success      sql.NullBool   `json:"success"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           int64          `json:"id"`
}

// ==========================================
// UPDATE OPERATIONS
// ==========================================
func (q *Queries) UpdateAutomationLogSuccess(ctx context.Context, arg UpdateAutomationLogSuccessParams) error {
	_, err := q.exec(ctx, q.updateAutomationLogSuccessStmt, updateAutomationLogSuccess, arg.Success, arg.ErrorMessage, arg.ID)
	return err
}

const updateAutomationLogTitle = `-- name: UpdateAutomationLogTitle :exec
UPDATE automation_logs
SET title = ?
WHERE id = ?
`

type UpdateAutomationLogTitleParams struct {
	Title string `json:"title"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateAutomationLogTitle(ctx context.Context, arg UpdateAutomationLogTitleParams) error {
	_, err := q.exec(ctx, q.updateAutomationLogTitleStmt, updateAutomationLogTitle, arg.Title, arg.ID)
	return err
}
