// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.checkRecentChanges5minStmt, err = db.PrepareContext(ctx, checkRecentChanges5min); err != nil {
		return nil, fmt.Errorf("error preparing query CheckRecentChanges5min: %w", err)
	}
	if q.clearAllAutomationLogsStmt, err = db.PrepareContext(ctx, clearAllAutomationLogs); err != nil {
		return nil, fmt.Errorf("error preparing query ClearAllAutomationLogs: %w", err)
	}
	if q.countAutomationLogsStmt, err = db.PrepareContext(ctx, countAutomationLogs); err != nil {
		return nil, fmt.Errorf("error preparing query CountAutomationLogs: %w", err)
	}
	if q.countAutomationLogsByActionStmt, err = db.PrepareContext(ctx, countAutomationLogsByAction); err != nil {
		return nil, fmt.Errorf("error preparing query CountAutomationLogsByAction: %w", err)
	}
	if q.countAutomationLogsByNameStmt, err = db.PrepareContext(ctx, countAutomationLogsByName); err != nil {
		return nil, fmt.Errorf("error preparing query CountAutomationLogsByName: %w", err)
	}
	if q.countFailedLogsStmt, err = db.PrepareContext(ctx, countFailedLogs); err != nil {
		return nil, fmt.Errorf("error preparing query CountFailedLogs: %w", err)
	}
	if q.countLogsByDateRangeStmt, err = db.PrepareContext(ctx, countLogsByDateRange); err != nil {
		return nil, fmt.Errorf("error preparing query CountLogsByDateRange: %w", err)
	}
	if q.countRecentLogsStmt, err = db.PrepareContext(ctx, countRecentLogs); err != nil {
		return nil, fmt.Errorf("error preparing query CountRecentLogs: %w", err)
	}
	if q.countSuccessfulLogsStmt, err = db.PrepareContext(ctx, countSuccessfulLogs); err != nil {
		return nil, fmt.Errorf("error preparing query CountSuccessfulLogs: %w", err)
	}
	if q.countTodaysLogsStmt, err = db.PrepareContext(ctx, countTodaysLogs); err != nil {
		return nil, fmt.Errorf("error preparing query CountTodaysLogs: %w", err)
	}
	if q.createAutomationLogStmt, err = db.PrepareContext(ctx, createAutomationLog); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAutomationLog: %w", err)
	}
	if q.createAutomationLogWithTimestampStmt, err = db.PrepareContext(ctx, createAutomationLogWithTimestamp); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAutomationLogWithTimestamp: %w", err)
	}
	if q.deleteAfter30minStmt, err = db.PrepareContext(ctx, deleteAfter30min); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAfter30min: %w", err)
	}
	if q.deleteAutomationLogStmt, err = db.PrepareContext(ctx, deleteAutomationLog); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAutomationLog: %w", err)
	}
	if q.deleteAutomationLogsByActionStmt, err = db.PrepareContext(ctx, deleteAutomationLogsByAction); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAutomationLogsByAction: %w", err)
	}
	if q.deleteAutomationLogsByNameStmt, err = db.PrepareContext(ctx, deleteAutomationLogsByName); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAutomationLogsByName: %w", err)
	}
	if q.deleteFailedLogsStmt, err = db.PrepareContext(ctx, deleteFailedLogs); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFailedLogs: %w", err)
	}
	if q.deleteLogsByDateRangeStmt, err = db.PrepareContext(ctx, deleteLogsByDateRange); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteLogsByDateRange: %w", err)
	}
	if q.deleteOldAutomationLogsStmt, err = db.PrepareContext(ctx, deleteOldAutomationLogs); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOldAutomationLogs: %w", err)
	}
	if q.deleteOldAutomationLogsByDaysStmt, err = db.PrepareContext(ctx, deleteOldAutomationLogsByDays); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOldAutomationLogsByDays: %w", err)
	}
	if q.getActionTypeSummaryStmt, err = db.PrepareContext(ctx, getActionTypeSummary); err != nil {
		return nil, fmt.Errorf("error preparing query GetActionTypeSummary: %w", err)
	}
	if q.getAutomationLogStmt, err = db.PrepareContext(ctx, getAutomationLog); err != nil {
		return nil, fmt.Errorf("error preparing query GetAutomationLog: %w", err)
	}
	if q.getAutomationLogByNameStmt, err = db.PrepareContext(ctx, getAutomationLogByName); err != nil {
		return nil, fmt.Errorf("error preparing query GetAutomationLogByName: %w", err)
	}
	if q.getDailySummaryStmt, err = db.PrepareContext(ctx, getDailySummary); err != nil {
		return nil, fmt.Errorf("error preparing query GetDailySummary: %w", err)
	}
	if q.getDatabaseStatsStmt, err = db.PrepareContext(ctx, getDatabaseStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetDatabaseStats: %w", err)
	}
	if q.getHourlySummaryStmt, err = db.PrepareContext(ctx, getHourlySummary); err != nil {
		return nil, fmt.Errorf("error preparing query GetHourlySummary: %w", err)
	}
	if q.getLatestAutomationLogStmt, err = db.PrepareContext(ctx, getLatestAutomationLog); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestAutomationLog: %w", err)
	}
	if q.getLatestFailedLogStmt, err = db.PrepareContext(ctx, getLatestFailedLog); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestFailedLog: %w", err)
	}
	if q.getLatestSuccessfulLogStmt, err = db.PrepareContext(ctx, getLatestSuccessfulLog); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestSuccessfulLog: %w", err)
	}
	if q.getLogSizeByActionStmt, err = db.PrepareContext(ctx, getLogSizeByAction); err != nil {
		return nil, fmt.Errorf("error preparing query GetLogSizeByAction: %w", err)
	}
	if q.getLogsFromLastDaysStmt, err = db.PrepareContext(ctx, getLogsFromLastDays); err != nil {
		return nil, fmt.Errorf("error preparing query GetLogsFromLastDays: %w", err)
	}
	if q.getLogsFromLastHoursStmt, err = db.PrepareContext(ctx, getLogsFromLastHours); err != nil {
		return nil, fmt.Errorf("error preparing query GetLogsFromLastHours: %w", err)
	}
	if q.getLogsFromLastMinutesStmt, err = db.PrepareContext(ctx, getLogsFromLastMinutes); err != nil {
		return nil, fmt.Errorf("error preparing query GetLogsFromLastMinutes: %w", err)
	}
	if q.getMostCommonPixelColorsStmt, err = db.PrepareContext(ctx, getMostCommonPixelColors); err != nil {
		return nil, fmt.Errorf("error preparing query GetMostCommonPixelColors: %w", err)
	}
	if q.getMostUsedPositionsStmt, err = db.PrepareContext(ctx, getMostUsedPositions); err != nil {
		return nil, fmt.Errorf("error preparing query GetMostUsedPositions: %w", err)
	}
	if q.getRecentAutomationLogsStmt, err = db.PrepareContext(ctx, getRecentAutomationLogs); err != nil {
		return nil, fmt.Errorf("error preparing query GetRecentAutomationLogs: %w", err)
	}
	if q.getTodaysLogsStmt, err = db.PrepareContext(ctx, getTodaysLogs); err != nil {
		return nil, fmt.Errorf("error preparing query GetTodaysLogs: %w", err)
	}
	if q.getYesterdaysLogsStmt, err = db.PrepareContext(ctx, getYesterdaysLogs); err != nil {
		return nil, fmt.Errorf("error preparing query GetYesterdaysLogs: %w", err)
	}
	if q.listAutomationLogsStmt, err = db.PrepareContext(ctx, listAutomationLogs); err != nil {
		return nil, fmt.Errorf("error preparing query ListAutomationLogs: %w", err)
	}
	if q.listAutomationLogsByActionStmt, err = db.PrepareContext(ctx, listAutomationLogsByAction); err != nil {
		return nil, fmt.Errorf("error preparing query ListAutomationLogsByAction: %w", err)
	}
	if q.listAutomationLogsByNameStmt, err = db.PrepareContext(ctx, listAutomationLogsByName); err != nil {
		return nil, fmt.Errorf("error preparing query ListAutomationLogsByName: %w", err)
	}
	if q.listAutomationLogsByTitleStmt, err = db.PrepareContext(ctx, listAutomationLogsByTitle); err != nil {
		return nil, fmt.Errorf("error preparing query ListAutomationLogsByTitle: %w", err)
	}
	if q.listFailedLogsStmt, err = db.PrepareContext(ctx, listFailedLogs); err != nil {
		return nil, fmt.Errorf("error preparing query ListFailedLogs: %w", err)
	}
	if q.listLogsByDateRangeStmt, err = db.PrepareContext(ctx, listLogsByDateRange); err != nil {
		return nil, fmt.Errorf("error preparing query ListLogsByDateRange: %w", err)
	}
	if q.listLogsByPixelColorStmt, err = db.PrepareContext(ctx, listLogsByPixelColor); err != nil {
		return nil, fmt.Errorf("error preparing query ListLogsByPixelColor: %w", err)
	}
	if q.listLogsByPositionStmt, err = db.PrepareContext(ctx, listLogsByPosition); err != nil {
		return nil, fmt.Errorf("error preparing query ListLogsByPosition: %w", err)
	}
	if q.listSuccessfulLogsStmt, err = db.PrepareContext(ctx, listSuccessfulLogs); err != nil {
		return nil, fmt.Errorf("error preparing query ListSuccessfulLogs: %w", err)
	}
	if q.searchLogsByErrorMessageStmt, err = db.PrepareContext(ctx, searchLogsByErrorMessage); err != nil {
		return nil, fmt.Errorf("error preparing query SearchLogsByErrorMessage: %w", err)
	}
	if q.searchLogsByNameOrTitleStmt, err = db.PrepareContext(ctx, searchLogsByNameOrTitle); err != nil {
		return nil, fmt.Errorf("error preparing query SearchLogsByNameOrTitle: %w", err)
	}
	if q.updateAutomationLogNameStmt, err = db.PrepareContext(ctx, updateAutomationLogName); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAutomationLogName: %w", err)
	}
	if q.updateAutomationLogPixelColorStmt, err = db.PrepareContext(ctx, updateAutomationLogPixelColor); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAutomationLogPixelColor: %w", err)
	}
	if q.updateAutomationLogPositionStmt, err = db.PrepareContext(ctx, updateAutomationLogPosition); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAutomationLogPosition: %w", err)
	}
	if q.updateAutomationLogSuccessStmt, err = db.PrepareContext(ctx, updateAutomationLogSuccess); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAutomationLogSuccess: %w", err)
	}
	if q.updateAutomationLogTitleStmt, err = db.PrepareContext(ctx, updateAutomationLogTitle); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAutomationLogTitle: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.checkRecentChanges5minStmt != nil {
		if cerr := q.checkRecentChanges5minStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkRecentChanges5minStmt: %w", cerr)
		}
	}
	if q.clearAllAutomationLogsStmt != nil {
		if cerr := q.clearAllAutomationLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearAllAutomationLogsStmt: %w", cerr)
		}
	}
	if q.countAutomationLogsStmt != nil {
		if cerr := q.countAutomationLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAutomationLogsStmt: %w", cerr)
		}
	}
	if q.countAutomationLogsByActionStmt != nil {
		if cerr := q.countAutomationLogsByActionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAutomationLogsByActionStmt: %w", cerr)
		}
	}
	if q.countAutomationLogsByNameStmt != nil {
		if cerr := q.countAutomationLogsByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAutomationLogsByNameStmt: %w", cerr)
		}
	}
	if q.countFailedLogsStmt != nil {
		if cerr := q.countFailedLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countFailedLogsStmt: %w", cerr)
		}
	}
	if q.countLogsByDateRangeStmt != nil {
		if cerr := q.countLogsByDateRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countLogsByDateRangeStmt: %w", cerr)
		}
	}
	if q.countRecentLogsStmt != nil {
		if cerr := q.countRecentLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countRecentLogsStmt: %w", cerr)
		}
	}
	if q.countSuccessfulLogsStmt != nil {
		if cerr := q.countSuccessfulLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countSuccessfulLogsStmt: %w", cerr)
		}
	}
	if q.countTodaysLogsStmt != nil {
		if cerr := q.countTodaysLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countTodaysLogsStmt: %w", cerr)
		}
	}
	if q.createAutomationLogStmt != nil {
		if cerr := q.createAutomationLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAutomationLogStmt: %w", cerr)
		}
	}
	if q.createAutomationLogWithTimestampStmt != nil {
		if cerr := q.createAutomationLogWithTimestampStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAutomationLogWithTimestampStmt: %w", cerr)
		}
	}
	if q.deleteAfter30minStmt != nil {
		if cerr := q.deleteAfter30minStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAfter30minStmt: %w", cerr)
		}
	}
	if q.deleteAutomationLogStmt != nil {
		if cerr := q.deleteAutomationLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAutomationLogStmt: %w", cerr)
		}
	}
	if q.deleteAutomationLogsByActionStmt != nil {
		if cerr := q.deleteAutomationLogsByActionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAutomationLogsByActionStmt: %w", cerr)
		}
	}
	if q.deleteAutomationLogsByNameStmt != nil {
		if cerr := q.deleteAutomationLogsByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAutomationLogsByNameStmt: %w", cerr)
		}
	}
	if q.deleteFailedLogsStmt != nil {
		if cerr := q.deleteFailedLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFailedLogsStmt: %w", cerr)
		}
	}
	if q.deleteLogsByDateRangeStmt != nil {
		if cerr := q.deleteLogsByDateRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteLogsByDateRangeStmt: %w", cerr)
		}
	}
	if q.deleteOldAutomationLogsStmt != nil {
		if cerr := q.deleteOldAutomationLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOldAutomationLogsStmt: %w", cerr)
		}
	}
	if q.deleteOldAutomationLogsByDaysStmt != nil {
		if cerr := q.deleteOldAutomationLogsByDaysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOldAutomationLogsByDaysStmt: %w", cerr)
		}
	}
	if q.getActionTypeSummaryStmt != nil {
		if cerr := q.getActionTypeSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActionTypeSummaryStmt: %w", cerr)
		}
	}
	if q.getAutomationLogStmt != nil {
		if cerr := q.getAutomationLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAutomationLogStmt: %w", cerr)
		}
	}
	if q.getAutomationLogByNameStmt != nil {
		if cerr := q.getAutomationLogByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAutomationLogByNameStmt: %w", cerr)
		}
	}
	if q.getDailySummaryStmt != nil {
		if cerr := q.getDailySummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDailySummaryStmt: %w", cerr)
		}
	}
	if q.getDatabaseStatsStmt != nil {
		if cerr := q.getDatabaseStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDatabaseStatsStmt: %w", cerr)
		}
	}
	if q.getHourlySummaryStmt != nil {
		if cerr := q.getHourlySummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHourlySummaryStmt: %w", cerr)
		}
	}
	if q.getLatestAutomationLogStmt != nil {
		if cerr := q.getLatestAutomationLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestAutomationLogStmt: %w", cerr)
		}
	}
	if q.getLatestFailedLogStmt != nil {
		if cerr := q.getLatestFailedLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestFailedLogStmt: %w", cerr)
		}
	}
	if q.getLatestSuccessfulLogStmt != nil {
		if cerr := q.getLatestSuccessfulLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestSuccessfulLogStmt: %w", cerr)
		}
	}
	if q.getLogSizeByActionStmt != nil {
		if cerr := q.getLogSizeByActionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLogSizeByActionStmt: %w", cerr)
		}
	}
	if q.getLogsFromLastDaysStmt != nil {
		if cerr := q.getLogsFromLastDaysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLogsFromLastDaysStmt: %w", cerr)
		}
	}
	if q.getLogsFromLastHoursStmt != nil {
		if cerr := q.getLogsFromLastHoursStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLogsFromLastHoursStmt: %w", cerr)
		}
	}
	if q.getLogsFromLastMinutesStmt != nil {
		if cerr := q.getLogsFromLastMinutesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLogsFromLastMinutesStmt: %w", cerr)
		}
	}
	if q.getMostCommonPixelColorsStmt != nil {
		if cerr := q.getMostCommonPixelColorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMostCommonPixelColorsStmt: %w", cerr)
		}
	}
	if q.getMostUsedPositionsStmt != nil {
		if cerr := q.getMostUsedPositionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMostUsedPositionsStmt: %w", cerr)
		}
	}
	if q.getRecentAutomationLogsStmt != nil {
		if cerr := q.getRecentAutomationLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRecentAutomationLogsStmt: %w", cerr)
		}
	}
	if q.getTodaysLogsStmt != nil {
		if cerr := q.getTodaysLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTodaysLogsStmt: %w", cerr)
		}
	}
	if q.getYesterdaysLogsStmt != nil {
		if cerr := q.getYesterdaysLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getYesterdaysLogsStmt: %w", cerr)
		}
	}
	if q.listAutomationLogsStmt != nil {
		if cerr := q.listAutomationLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAutomationLogsStmt: %w", cerr)
		}
	}
	if q.listAutomationLogsByActionStmt != nil {
		if cerr := q.listAutomationLogsByActionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAutomationLogsByActionStmt: %w", cerr)
		}
	}
	if q.listAutomationLogsByNameStmt != nil {
		if cerr := q.listAutomationLogsByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAutomationLogsByNameStmt: %w", cerr)
		}
	}
	if q.listAutomationLogsByTitleStmt != nil {
		if cerr := q.listAutomationLogsByTitleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAutomationLogsByTitleStmt: %w", cerr)
		}
	}
	if q.listFailedLogsStmt != nil {
		if cerr := q.listFailedLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFailedLogsStmt: %w", cerr)
		}
	}
	if q.listLogsByDateRangeStmt != nil {
		if cerr := q.listLogsByDateRangeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLogsByDateRangeStmt: %w", cerr)
		}
	}
	if q.listLogsByPixelColorStmt != nil {
		if cerr := q.listLogsByPixelColorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLogsByPixelColorStmt: %w", cerr)
		}
	}
	if q.listLogsByPositionStmt != nil {
		if cerr := q.listLogsByPositionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLogsByPositionStmt: %w", cerr)
		}
	}
	if q.listSuccessfulLogsStmt != nil {
		if cerr := q.listSuccessfulLogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSuccessfulLogsStmt: %w", cerr)
		}
	}
	if q.searchLogsByErrorMessageStmt != nil {
		if cerr := q.searchLogsByErrorMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchLogsByErrorMessageStmt: %w", cerr)
		}
	}
	if q.searchLogsByNameOrTitleStmt != nil {
		if cerr := q.searchLogsByNameOrTitleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchLogsByNameOrTitleStmt: %w", cerr)
		}
	}
	if q.updateAutomationLogNameStmt != nil {
		if cerr := q.updateAutomationLogNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAutomationLogNameStmt: %w", cerr)
		}
	}
	if q.updateAutomationLogPixelColorStmt != nil {
		if cerr := q.updateAutomationLogPixelColorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAutomationLogPixelColorStmt: %w", cerr)
		}
	}
	if q.updateAutomationLogPositionStmt != nil {
		if cerr := q.updateAutomationLogPositionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAutomationLogPositionStmt: %w", cerr)
		}
	}
	if q.updateAutomationLogSuccessStmt != nil {
		if cerr := q.updateAutomationLogSuccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAutomationLogSuccessStmt: %w", cerr)
		}
	}
	if q.updateAutomationLogTitleStmt != nil {
		if cerr := q.updateAutomationLogTitleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAutomationLogTitleStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                   DBTX
	tx                                   *sql.Tx
	checkRecentChanges5minStmt           *sql.Stmt
	clearAllAutomationLogsStmt           *sql.Stmt
	countAutomationLogsStmt              *sql.Stmt
	countAutomationLogsByActionStmt      *sql.Stmt
	countAutomationLogsByNameStmt        *sql.Stmt
	countFailedLogsStmt                  *sql.Stmt
	countLogsByDateRangeStmt             *sql.Stmt
	countRecentLogsStmt                  *sql.Stmt
	countSuccessfulLogsStmt              *sql.Stmt
	countTodaysLogsStmt                  *sql.Stmt
	createAutomationLogStmt              *sql.Stmt
	createAutomationLogWithTimestampStmt *sql.Stmt
	deleteAfter30minStmt                 *sql.Stmt
	deleteAutomationLogStmt              *sql.Stmt
	deleteAutomationLogsByActionStmt     *sql.Stmt
	deleteAutomationLogsByNameStmt       *sql.Stmt
	deleteFailedLogsStmt                 *sql.Stmt
	deleteLogsByDateRangeStmt            *sql.Stmt
	deleteOldAutomationLogsStmt          *sql.Stmt
	deleteOldAutomationLogsByDaysStmt    *sql.Stmt
	getActionTypeSummaryStmt             *sql.Stmt
	getAutomationLogStmt                 *sql.Stmt
	getAutomationLogByNameStmt           *sql.Stmt
	getDailySummaryStmt                  *sql.Stmt
	getDatabaseStatsStmt                 *sql.Stmt
	getHourlySummaryStmt                 *sql.Stmt
	getLatestAutomationLogStmt           *sql.Stmt
	getLatestFailedLogStmt               *sql.Stmt
	getLatestSuccessfulLogStmt           *sql.Stmt
	getLogSizeByActionStmt               *sql.Stmt
	getLogsFromLastDaysStmt              *sql.Stmt
	getLogsFromLastHoursStmt             *sql.Stmt
	getLogsFromLastMinutesStmt           *sql.Stmt
	getMostCommonPixelColorsStmt         *sql.Stmt
	getMostUsedPositionsStmt             *sql.Stmt
	getRecentAutomationLogsStmt          *sql.Stmt
	getTodaysLogsStmt                    *sql.Stmt
	getYesterdaysLogsStmt                *sql.Stmt
	listAutomationLogsStmt               *sql.Stmt
	listAutomationLogsByActionStmt       *sql.Stmt
	listAutomationLogsByNameStmt         *sql.Stmt
	listAutomationLogsByTitleStmt        *sql.Stmt
	listFailedLogsStmt                   *sql.Stmt
	listLogsByDateRangeStmt              *sql.Stmt
	listLogsByPixelColorStmt             *sql.Stmt
	listLogsByPositionStmt               *sql.Stmt
	listSuccessfulLogsStmt               *sql.Stmt
	searchLogsByErrorMessageStmt         *sql.Stmt
	searchLogsByNameOrTitleStmt          *sql.Stmt
	updateAutomationLogNameStmt          *sql.Stmt
	updateAutomationLogPixelColorStmt    *sql.Stmt
	updateAutomationLogPositionStmt      *sql.Stmt
	updateAutomationLogSuccessStmt       *sql.Stmt
	updateAutomationLogTitleStmt         *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                   tx,
		tx:                                   tx,
		checkRecentChanges5minStmt:           q.checkRecentChanges5minStmt,
		clearAllAutomationLogsStmt:           q.clearAllAutomationLogsStmt,
		countAutomationLogsStmt:              q.countAutomationLogsStmt,
		countAutomationLogsByActionStmt:      q.countAutomationLogsByActionStmt,
		countAutomationLogsByNameStmt:        q.countAutomationLogsByNameStmt,
		countFailedLogsStmt:                  q.countFailedLogsStmt,
		countLogsByDateRangeStmt:             q.countLogsByDateRangeStmt,
		countRecentLogsStmt:                  q.countRecentLogsStmt,
		countSuccessfulLogsStmt:              q.countSuccessfulLogsStmt,
		countTodaysLogsStmt:                  q.countTodaysLogsStmt,
		createAutomationLogStmt:              q.createAutomationLogStmt,
		createAutomationLogWithTimestampStmt: q.createAutomationLogWithTimestampStmt,
		deleteAfter30minStmt:                 q.deleteAfter30minStmt,
		deleteAutomationLogStmt:              q.deleteAutomationLogStmt,
		deleteAutomationLogsByActionStmt:     q.deleteAutomationLogsByActionStmt,
		deleteAutomationLogsByNameStmt:       q.deleteAutomationLogsByNameStmt,
		deleteFailedLogsStmt:                 q.deleteFailedLogsStmt,
		deleteLogsByDateRangeStmt:            q.deleteLogsByDateRangeStmt,
		deleteOldAutomationLogsStmt:          q.deleteOldAutomationLogsStmt,
		deleteOldAutomationLogsByDaysStmt:    q.deleteOldAutomationLogsByDaysStmt,
		getActionTypeSummaryStmt:             q.getActionTypeSummaryStmt,
		getAutomationLogStmt:                 q.getAutomationLogStmt,
		getAutomationLogByNameStmt:           q.getAutomationLogByNameStmt,
		getDailySummaryStmt:                  q.getDailySummaryStmt,
		getDatabaseStatsStmt:                 q.getDatabaseStatsStmt,
		getHourlySummaryStmt:                 q.getHourlySummaryStmt,
		getLatestAutomationLogStmt:           q.getLatestAutomationLogStmt,
		getLatestFailedLogStmt:               q.getLatestFailedLogStmt,
		getLatestSuccessfulLogStmt:           q.getLatestSuccessfulLogStmt,
		getLogSizeByActionStmt:               q.getLogSizeByActionStmt,
		getLogsFromLastDaysStmt:              q.getLogsFromLastDaysStmt,
		getLogsFromLastHoursStmt:             q.getLogsFromLastHoursStmt,
		getLogsFromLastMinutesStmt:           q.getLogsFromLastMinutesStmt,
		getMostCommonPixelColorsStmt:         q.getMostCommonPixelColorsStmt,
		getMostUsedPositionsStmt:             q.getMostUsedPositionsStmt,
		getRecentAutomationLogsStmt:          q.getRecentAutomationLogsStmt,
		getTodaysLogsStmt:                    q.getTodaysLogsStmt,
		getYesterdaysLogsStmt:                q.getYesterdaysLogsStmt,
		listAutomationLogsStmt:               q.listAutomationLogsStmt,
		listAutomationLogsByActionStmt:       q.listAutomationLogsByActionStmt,
		listAutomationLogsByNameStmt:         q.listAutomationLogsByNameStmt,
		listAutomationLogsByTitleStmt:        q.listAutomationLogsByTitleStmt,
		listFailedLogsStmt:                   q.listFailedLogsStmt,
		listLogsByDateRangeStmt:              q.listLogsByDateRangeStmt,
		listLogsByPixelColorStmt:             q.listLogsByPixelColorStmt,
		listLogsByPositionStmt:               q.listLogsByPositionStmt,
		listSuccessfulLogsStmt:               q.listSuccessfulLogsStmt,
		searchLogsByErrorMessageStmt:         q.searchLogsByErrorMessageStmt,
		searchLogsByNameOrTitleStmt:          q.searchLogsByNameOrTitleStmt,
		updateAutomationLogNameStmt:          q.updateAutomationLogNameStmt,
		updateAutomationLogPixelColorStmt:    q.updateAutomationLogPixelColorStmt,
		updateAutomationLogPositionStmt:      q.updateAutomationLogPositionStmt,
		updateAutomationLogSuccessStmt:       q.updateAutomationLogSuccessStmt,
		updateAutomationLogTitleStmt:         q.updateAutomationLogTitleStmt,
	}
}
