// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type AutomationLog struct {
	ID           int64           `json:"id"`
	Name         string          `json:"name"`
	Title        string          `json:"title"`
	ActionType   string          `json:"action_type"`
	XPosition    sql.NullFloat64 `json:"x_position"`
	YPosition    sql.NullFloat64 `json:"y_position"`
	PixelColor   sql.NullString  `json:"pixel_color"`
	CreateAt     sql.NullTime    `json:"create_at"`
	Success      sql.NullBool    `json:"success"`
	ErrorMessage sql.NullString  `json:"error_message"`
}
