// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CheckRecentChanges5min(ctx context.Context) ([]CheckRecentChanges5minRow, error)
	ClearAllAutomationLogs(ctx context.Context) error
	// ==========================================
	// COUNT OPERATIONS
	// ==========================================
	CountAutomationLogs(ctx context.Context) (int64, error)
	CountAutomationLogsByAction(ctx context.Context, actionType string) (int64, error)
	CountAutomationLogsByName(ctx context.Context, name string) (int64, error)
	CountFailedLogs(ctx context.Context) (int64, error)
	CountLogsByDateRange(ctx context.Context, arg CountLogsByDateRangeParams) (int64, error)
	CountRecentLogs(ctx context.Context) (int64, error)
	CountSuccessfulLogs(ctx context.Context) (int64, error)
	CountTodaysLogs(ctx context.Context) (int64, error)
	// ==========================================
	// CREATE OPERATIONS
	// ==========================================
	CreateAutomationLog(ctx context.Context, arg CreateAutomationLogParams) (AutomationLog, error)
	CreateAutomationLogWithTimestamp(ctx context.Context, arg CreateAutomationLogWithTimestampParams) (AutomationLog, error)
	DeleteAfter30min(ctx context.Context) error
	// ==========================================
	// DELETE OPERATIONS
	// ==========================================
	DeleteAutomationLog(ctx context.Context, id int64) error
	DeleteAutomationLogsByAction(ctx context.Context, actionType string) error
	DeleteAutomationLogsByName(ctx context.Context, name string) error
	DeleteFailedLogs(ctx context.Context) error
	DeleteLogsByDateRange(ctx context.Context, arg DeleteLogsByDateRangeParams) error
	DeleteOldAutomationLogs(ctx context.Context) error
	DeleteOldAutomationLogsByDays(ctx context.Context, dollar_1 sql.NullString) error
	// ==========================================
	// AGGREGATE OPERATIONS
	// ==========================================
	GetActionTypeSummary(ctx context.Context) ([]GetActionTypeSummaryRow, error)
	// ==========================================
	// READ OPERATIONS - Single Record
	// ==========================================
	GetAutomationLog(ctx context.Context, id int64) (AutomationLog, error)
	GetAutomationLogByName(ctx context.Context, name string) (AutomationLog, error)
	GetDailySummary(ctx context.Context) ([]GetDailySummaryRow, error)
	// ==========================================
	// UTILITY OPERATIONS
	// ==========================================
	GetDatabaseStats(ctx context.Context) (GetDatabaseStatsRow, error)
	GetHourlySummary(ctx context.Context) ([]GetHourlySummaryRow, error)
	GetLatestAutomationLog(ctx context.Context) (AutomationLog, error)
	GetLatestFailedLog(ctx context.Context) (AutomationLog, error)
	GetLatestSuccessfulLog(ctx context.Context) (AutomationLog, error)
	GetLogSizeByAction(ctx context.Context) ([]GetLogSizeByActionRow, error)
	GetLogsFromLastDays(ctx context.Context, dollar_1 sql.NullString) ([]AutomationLog, error)
	GetLogsFromLastHours(ctx context.Context, dollar_1 sql.NullString) ([]AutomationLog, error)
	GetLogsFromLastMinutes(ctx context.Context, dollar_1 sql.NullString) ([]AutomationLog, error)
	GetMostCommonPixelColors(ctx context.Context, limit int64) ([]GetMostCommonPixelColorsRow, error)
	GetMostUsedPositions(ctx context.Context, limit int64) ([]GetMostUsedPositionsRow, error)
	// ==========================================
	// READ OPERATIONS - Time-based Queries
	// ==========================================
	GetRecentAutomationLogs(ctx context.Context) ([]AutomationLog, error)
	GetTodaysLogs(ctx context.Context) ([]AutomationLog, error)
	GetYesterdaysLogs(ctx context.Context) ([]AutomationLog, error)
	// ==========================================
	// READ OPERATIONS - Multiple Records
	// ==========================================
	ListAutomationLogs(ctx context.Context, limit int64) ([]AutomationLog, error)
	ListAutomationLogsByAction(ctx context.Context, arg ListAutomationLogsByActionParams) ([]AutomationLog, error)
	ListAutomationLogsByName(ctx context.Context, arg ListAutomationLogsByNameParams) ([]AutomationLog, error)
	ListAutomationLogsByTitle(ctx context.Context, arg ListAutomationLogsByTitleParams) ([]AutomationLog, error)
	ListFailedLogs(ctx context.Context, limit int64) ([]AutomationLog, error)
	ListLogsByDateRange(ctx context.Context, arg ListLogsByDateRangeParams) ([]AutomationLog, error)
	ListLogsByPixelColor(ctx context.Context, arg ListLogsByPixelColorParams) ([]AutomationLog, error)
	ListLogsByPosition(ctx context.Context, arg ListLogsByPositionParams) ([]AutomationLog, error)
	ListSuccessfulLogs(ctx context.Context, limit int64) ([]AutomationLog, error)
	// ==========================================
	// SEARCH OPERATIONS
	// ==========================================
	SearchLogsByErrorMessage(ctx context.Context, arg SearchLogsByErrorMessageParams) ([]AutomationLog, error)
	SearchLogsByNameOrTitle(ctx context.Context, arg SearchLogsByNameOrTitleParams) ([]AutomationLog, error)
	UpdateAutomationLogName(ctx context.Context, arg UpdateAutomationLogNameParams) error
	UpdateAutomationLogPixelColor(ctx context.Context, arg UpdateAutomationLogPixelColorParams) error
	UpdateAutomationLogPosition(ctx context.Context, arg UpdateAutomationLogPositionParams) error
	// ==========================================
	// UPDATE OPERATIONS
	// ==========================================
	UpdateAutomationLogSuccess(ctx context.Context, arg UpdateAutomationLogSuccessParams) error
	UpdateAutomationLogTitle(ctx context.Context, arg UpdateAutomationLogTitleParams) error
}

var _ Querier = (*Queries)(nil)
