// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: time_analysis.sql

package sqlc

import (
	"context"
)

const checkRecentChanges5min = `-- name: CheckRecentChanges5min :many
SELECT
    name,
    title,
    Count(pixel_color) as total_pixel,
    COUNT(DISTINCT pixel_color) as total_unique_pixel
FROM automation_logs
WHERE create_at >= datetime('now', '-5 minutes')
GROUP BY title,name
`

type CheckRecentChanges5minRow struct {
	Name             string `json:"name"`
	Title            string `json:"title"`
	TotalPixel       int64  `json:"total_pixel"`
	TotalUniquePixel int64  `json:"total_unique_pixel"`
}

func (q *Queries) CheckRecentChanges5min(ctx context.Context) ([]CheckRecentChanges5minRow, error) {
	rows, err := q.query(ctx, q.checkRecentChanges5minStmt, checkRecentChanges5min)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckRecentChanges5minRow{}
	for rows.Next() {
		var i CheckRecentChanges5minRow
		if err := rows.Scan(
			&i.Name,
			&i.Title,
			&i.TotalPixel,
			&i.TotalUniquePixel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAfter30min = `-- name: DeleteAfter30min :exec
DELETE FROM automation_logs
WHERE create_at < datetime('now', '-30 minutes')
`

func (q *Queries) DeleteAfter30min(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteAfter30minStmt, deleteAfter30min)
	return err
}
